SPECIAL>CLEARRUNS
SIMULATE>BASED|
SIMULATE>PAYOFF|

{fig 5: Three basic scenarios}

SIMULATE>RUNNAME|figures\fig5_scen1.vdf
SIMULATE>SETVAL|tau=0.5
SIMULATE>SETVAL|SWITCH OPEN=0
MENU>RUN|o
MENU>VDF2TAB|figures\fig5_scen1.vdf|figures\fig5_scen1.tab||*

SIMULATE>RUNNAME|figures\fig5_scen2.vdf
SIMULATE>SETVAL|tau=1
SIMULATE>SETVAL|SWITCH OPEN=0
MENU>RUN|o
MENU>VDF2TAB|figures\fig5_scen2.vdf|figures\fig5_scen2.tab||*

SIMULATE>RUNNAME|figures\fig5_scen3.vdf
SIMULATE>SETVAL|tau=1
SIMULATE>SETVAL|SWITCH OPEN=1
MENU>RUN|o
MENU>VDF2TAB|figures\fig5_scen3.vdf|figures\fig5_scen3.tab||*


SPECIAL>CLEARRUNS

{fig 4: Growth phase without open interfaces}

SIMULATE>RUNNAME|figures\fig4_05_4.vdf
SIMULATE>SETVAL|SWITCH FULL CE=1
SIMULATE>SETVAL|SWITCH OPEN=0
SIMULATE>SETVAL|tau=0.5
SIMULATE>SETVAL|T=4
MENU>RUN|o
MENU>VDF2TAB|figures\fig4_05_4.vdf|figures\fig4_05_4.tab|figures\fig_savelist.lst|*
SPECIAL>CLEARRUNS

SIMULATE>RUNNAME|figures\fig4_05_6.vdf
SIMULATE>SETVAL|SWITCH FULL CE=1
SIMULATE>SETVAL|SWITCH OPEN=0
SIMULATE>SETVAL|tau=0.5
SIMULATE>SETVAL|T=6
MENU>RUN|o
MENU>VDF2TAB|figures\fig4_05_6.vdf|figures\fig4_05_6.tab|figures\fig_savelist.lst|*
SPECIAL>CLEARRUNS

SIMULATE>RUNNAME|figures\fig4_075_3.vdf
SIMULATE>SETVAL|SWITCH FULL CE=1
SIMULATE>SETVAL|SWITCH OPEN=0
SIMULATE>SETVAL|tau=0.75
SIMULATE>SETVAL|T=3
MENU>RUN|o
MENU>VDF2TAB|figures\fig4_075_3.vdf|figures\fig4_075_3.tab|figures\fig_savelist.lst|*
SPECIAL>CLEARRUNS

SIMULATE>RUNNAME|figures\fig4_075_4.vdf
SIMULATE>SETVAL|SWITCH FULL CE=1
SIMULATE>SETVAL|SWITCH OPEN=0
SIMULATE>SETVAL|tau=0.75
SIMULATE>SETVAL|T=4
MENU>RUN|o
MENU>VDF2TAB|figures\fig4_075_4.vdf|figures\fig4_075_4.tab|figures\fig_savelist.lst|*
SPECIAL>CLEARRUNS

SIMULATE>RUNNAME|figures\fig4_075_6.vdf
SIMULATE>SETVAL|SWITCH FULL CE=1
SIMULATE>SETVAL|SWITCH OPEN=0
SIMULATE>SETVAL|tau=0.75
SIMULATE>SETVAL|T=6
MENU>RUN|o
MENU>VDF2TAB|figures\fig4_075_6.vdf|figures\fig4_075_6.tab|figures\fig_savelist.lst|*
SPECIAL>CLEARRUNS

{fig 6: Growth phase with open interfaces}

SIMULATE>RUNNAME|figures\fig6_05_4.vdf
SIMULATE>SETVAL|SWITCH FULL CE=1
SIMULATE>SETVAL|SWITCH OPEN=1
SIMULATE>SETVAL|tau=0.5
SIMULATE>SETVAL|T=4
MENU>RUN|o
MENU>VDF2TAB|figures\fig6_05_4.vdf|figures\fig6_05_4.tab|figures\fig_savelist.lst|*
SPECIAL>CLEARRUNS

SIMULATE>RUNNAME|figures\fig6_05_6.vdf
SIMULATE>SETVAL|SWITCH FULL CE=1
SIMULATE>SETVAL|SWITCH OPEN=1
SIMULATE>SETVAL|tau=0.5
SIMULATE>SETVAL|T=6
MENU>RUN|o
MENU>VDF2TAB|figures\fig6_05_6.vdf|figures\fig6_05_6.tab|figures\fig_savelist.lst|*
SPECIAL>CLEARRUNS

SIMULATE>RUNNAME|figures\fig6_075_3.vdf
SIMULATE>SETVAL|SWITCH FULL CE=1
SIMULATE>SETVAL|SWITCH OPEN=1
SIMULATE>SETVAL|tau=0.75
SIMULATE>SETVAL|T=3
MENU>RUN|o
MENU>VDF2TAB|figures\fig6_075_3.vdf|figures\fig6_075_3.tab|figures\fig_savelist.lst|*
SPECIAL>CLEARRUNS

SIMULATE>RUNNAME|figures\fig6_075_4.vdf
SIMULATE>SETVAL|SWITCH FULL CE=1
SIMULATE>SETVAL|SWITCH OPEN=1
SIMULATE>SETVAL|tau=0.75
SIMULATE>SETVAL|T=4
MENU>RUN|o
MENU>VDF2TAB|figures\fig6_075_4.vdf|figures\fig6_075_4.tab|figures\fig_savelist.lst|*
SPECIAL>CLEARRUNS

SIMULATE>RUNNAME|figures\fig6_075_6.vdf
SIMULATE>SETVAL|SWITCH FULL CE=1
SIMULATE>SETVAL|SWITCH OPEN=1
SIMULATE>SETVAL|tau=0.75
SIMULATE>SETVAL|T=6
MENU>RUN|o
MENU>VDF2TAB|figures\fig6_075_6.vdf|figures\fig6_075_6.tab|figures\fig_savelist.lst|*
SPECIAL>CLEARRUNS

SIMULATE>SETVAL|T=4
SIMULATE>SETVAL|tau=1


{fig 8: Competition phase - no open interfaces}

SIMULATE>RUNNAME|figures\fig8_theta0.vdf
SIMULATE>SETVAL|SWITCH FULL CE=0
SIMULATE>SETVAL|SWITCH OPEN=0
SIMULATE>SETVAL|gamma'=3
SIMULATE>SETVAL|theta=0
SIMULATE>SETVAL|FINAL TIME=30
MENU>RUN|o
MENU>VDF2TAB|figures\fig8_theta0.vdf|figures\fig8_theta0.tab|figures\fig_savelist.lst|*
SPECIAL>CLEARRUNS

SIMULATE>RUNNAME|figures\fig8_theta05.vdf
SIMULATE>SETVAL|SWITCH FULL CE=0
SIMULATE>SETVAL|SWITCH OPEN=0
SIMULATE>SETVAL|gamma'=3
SIMULATE>SETVAL|theta=0.5
SIMULATE>SETVAL|FINAL TIME=30
MENU>RUN|o
MENU>VDF2TAB|figures\fig8_theta05.vdf|figures\fig8_theta05.tab|figures\fig_savelist.lst|*
SPECIAL>CLEARRUNS

SIMULATE>RUNNAME|figures\fig8_theta1.vdf
SIMULATE>SETVAL|SWITCH FULL CE=0
SIMULATE>SETVAL|SWITCH OPEN=0
SIMULATE>SETVAL|gamma'=3
SIMULATE>SETVAL|theta=1
SIMULATE>SETVAL|FINAL TIME=30
MENU>RUN|o
MENU>VDF2TAB|figures\fig8_theta1.vdf|figures\fig8_theta1.tab|figures\fig_savelist.lst|*
SPECIAL>CLEARRUNS

{fig 9: Competition phase - open interfaces gamma1}

SIMULATE>RUNNAME|figures\fig9_theta0.vdf
SIMULATE>SETVAL|SWITCH FULL CE=0
SIMULATE>SETVAL|SWITCH OPEN=1
SIMULATE>SETVAL|gamma'=1
SIMULATE>SETVAL|theta=0
SIMULATE>SETVAL|FINAL TIME=30
MENU>RUN|o
MENU>VDF2TAB|figures\fig9_theta0.vdf|figures\fig9_theta0.tab|figures\fig_savelist.lst|*
SPECIAL>CLEARRUNS

SIMULATE>RUNNAME|figures\fig9_theta05.vdf
SIMULATE>SETVAL|SWITCH FULL CE=0
SIMULATE>SETVAL|SWITCH OPEN=1
SIMULATE>SETVAL|gamma'=1
SIMULATE>SETVAL|theta=0.5
SIMULATE>SETVAL|FINAL TIME=30
MENU>RUN|o
MENU>VDF2TAB|figures\fig9_theta05.vdf|figures\fig9_theta05.tab|figures\fig_savelist.lst|*
SPECIAL>CLEARRUNS

SIMULATE>RUNNAME|figures\fig9_theta1.vdf
SIMULATE>SETVAL|SWITCH FULL CE=0
SIMULATE>SETVAL|SWITCH OPEN=1
SIMULATE>SETVAL|gamma'=1
SIMULATE>SETVAL|theta=1
SIMULATE>SETVAL|FINAL TIME=30
MENU>RUN|o
MENU>VDF2TAB|figures\fig9_theta1.vdf|figures\fig9_theta1.tab|figures\fig_savelist.lst|*
SPECIAL>CLEARRUNS


{fig 10: Competition phase - open interfaces gamma3}

SIMULATE>RUNNAME|figures\fig10_theta0.vdf
SIMULATE>SETVAL|SWITCH FULL CE=0
SIMULATE>SETVAL|SWITCH OPEN=1
SIMULATE>SETVAL|gamma'=3
SIMULATE>SETVAL|theta=0
SIMULATE>SETVAL|FINAL TIME=30
MENU>RUN|o
MENU>VDF2TAB|figures\fig10_theta0.vdf|figures\fig10_theta0.tab|figures\fig_savelist.lst|*
SPECIAL>CLEARRUNS

SIMULATE>RUNNAME|figures\fig10_theta05.vdf
SIMULATE>SETVAL|SWITCH FULL CE=0
SIMULATE>SETVAL|SWITCH OPEN=1
SIMULATE>SETVAL|gamma'=3
SIMULATE>SETVAL|theta=0.5
SIMULATE>SETVAL|FINAL TIME=30
MENU>RUN|o
MENU>VDF2TAB|figures\fig10_theta05.vdf|figures\fig10_theta05.tab|figures\fig_savelist.lst|*
SPECIAL>CLEARRUNS

SIMULATE>RUNNAME|figures\fig10_theta1.vdf
SIMULATE>SETVAL|SWITCH FULL CE=0
SIMULATE>SETVAL|SWITCH OPEN=1
SIMULATE>SETVAL|gamma'=3
SIMULATE>SETVAL|theta=1
SIMULATE>SETVAL|FINAL TIME=30
MENU>RUN|o
MENU>VDF2TAB|figures\fig10_theta1.vdf|figures\fig10_theta1.tab|figures\fig_savelist.lst|*
SPECIAL>CLEARRUNS

